### ISSUE TITLE
[Question]: OOM occurs when reproducing end-to-end latency tests with a single A100

### ISSUE THREAD

**Issue by HayeonLee** [microsoft/MInference#65]
### Describe the issue

Hi @iofu728, 
Thank you for your quick answers!
I have tried to reproduce the end-to-end latency tests  by following https://github.com/microsoft/MInference/tree/main/experiments#end-to-end-benchmark and encountered OOM errors with a single A100. I tested attn_type hf / minference / minference_with_dense / streaming and all of them occured OOMs. Do you have any comments to fix these errors? 

Thank you!

**Comment by iofu728** [comment]
Hi @hayeonLee,

Apologies for forgetting to include the `kv_cache_cpu` parameter in the documentation.

This is primarily because, with inputs greater than 700K, the memory overhead for activations during the linear operations of Attention becomes quite significant. In the "kv_cache_cpu" mode, we have further optimized the activations to manage this overhead.

You can run the following script:

```bash
python experiments/benchmarks/benchmark_e2e.py --attn_type minference --context_window 1_000_000 --kv_cache_cpu
python experiments/benchmarks/benchmark_e2e.py --attn_type minference_with_dense --context_window 1_000_000 --kv_cache_cpu
```

**Comment by HayeonLee** [comment]
@iofu728, Thank you for the update! (I confirmed that the code worked upto ~900K without `kv_cache_cpu`.)
