### ISSUE TITLE
[Question]: Memory measurement

### ISSUE THREAD

**Issue by HayeonLee** [microsoft/MInference#68]
### Describe the issue

Hi @iofu728,
While the memory measurement is not included the official code, if you don't mind, I have a question regarding it. 
I expected that the your code version streamingllm (attn_type=streaming) or MInference + SnapKV showed the memory reduction compared with full attention version (attn_type=minference_with_dense). However, the peak memory values are the same across attn_type=streaming, MInference + SnapKV, and attn_type=minference_with_dense. It seemed that your code version SnapKV conducted real KV cache drop, then why there is no memory reduction? Any insights or suggestions would be valuable! 

FYI,
I added the below code in latency measurement benchmark setting (experiments/benchmarks/benchmark_e2e.py)
`memory_allocated = torch.cuda.memory_allocated(device) / (1024 ** 2)`
`memory_reserved = torch.cuda.memory_reserved(device) / (1024 ** 2)`   
`peak_memory = torch.cuda.max_memory_allocated(device) / (1024 ** 2)`

**Comment by iofu728** [comment]
Hi @HayeonLee, thanks for your feedback.

This is because we did not save the KV cache in our end-to-end benchmark scripts to avoid OOM issues, or we used 'kv_cache_cpu' to move the KV cache to the CPU. If you want to measure the memory cost, you can set `use_cache` to `True` at https://github.com/microsoft/MInference/blob/main/experiments/benchmarks/benchmark_e2e.py#L33.

**Comment by HayeonLee** [comment]
Hi @iofu728, thank you for the suggestion! It worked successfully:D
