### ISSUE TITLE
[Question]: Intuition behind kernel search

### ISSUE THREAD

**Issue by PiotrNawrot** [microsoft/MInference#80]
### Describe the issue

Hey once again!

I was curious if you could share some intuition behind pattern search functions.

In `minference_forward.py` you have `search_pattern` and `search_pattern_v2`:
- in `search_pattern` you have this list of different vertical_and_slash patterns, but if the expected attention recall of the block_sparse (that recovers 1/8 of the blocks if I understand correctly) then you go with maximum vertical_and_slash configuration which is 1000, 6096
- on the other hand in `search_pattern_v2` the list for `vertical_and_slash` choices doesn't seem to be intuitive for me as imo only `(3500, 100), (1000, 4096)` are real candidates as `(1000, 4096)` is strictly recovering more attention scores than all the other options so it should also achieve better score (even though in this function we don't directly optimise for attention score recall), right?

FYI - I'm testing MInference with different levels of sparsity now and I'm wondering what's the best heuristic for choosing the number of slashes and verticals for each (layer, head). It would be amazing if you could share any recommendations.

Thanks in advance for your time!
Piotr

**Comment by iofu728** [comment]
Hi @PiotrNawrot, thank you for your question and support.

1. In the initial stages, we experimented with various search methods. As you noticed, there are two functions in the code: `search_pattern` and `search_pattern_v2`. However, we ultimately used the `search_pattern` function.
2. In the `search_pattern` function, we empirically replaced the block-sparse search result with (1000, 6096). During debugging, we found that the current version of block-sparse generalizes poorly for longer contexts. However, replacing it with the (1k, 2k) VS pattern worked much better. After tweaking both latency and performance, we settled on (1000, 6096), but you could set it to (1k, 2k) or even smaller. My current understanding is that this is because block-sparse isn’t accurate enough.
3. In `search_pattern_v2`, the (1k, 4k) setting serves as a backup. If the recall from the previous choices is low, we fall back to a higher sparsity rate.
4. Yes, the current approach does result in a lower sparsity rate. I look forward to seeing your experimental results.

Lastly, I personally think the current search method is not elegant enough, and there’s still plenty of room for improvement, especially regarding the accuracy of block-sparse.

Additionally, we build a benchmark project to analyze how different long-context methods perform in more realistic scenarios. Once it released, I’ll be happy to share it with you.

**Comment by PiotrNawrot** [comment]
Sounds great, thank you once again and looking forward to seeing your work!
