### ISSUE TITLE
[Question]: How to understand 32000 in patch.py ?

### ISSUE THREAD

**Issue by lemyx** [microsoft/MInference#93]
Dear authors,

Thanks for your great work.

I notice that there are lots of `32000` in [minference/patch.py](https://github.com/microsoft/MInference/blob/main/minference/patch.py).

May I ask what are the design purposes for there values?

**Comment by iofu728** [comment]
Hi @lemyx, thanks for your interest in MInference.  

The value **32000** refers to the chunk size used for chunk-wise processing of the MLP. This is designed to reduce peak GPU memory usage caused by activations. It’s part of our optimization for long-context LLM inference on a single A100 GPU. For more details, please see Appendix C.3.
